# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smslog',
            old_name='status_code',
            new_name='error_code',
        ),
    ]
