# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_auto_20170207_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='msg',
            field=models.CharField(default='sent', max_length=255),
        ),
    ]
