# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_smslog_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslog',
            name='msg',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='status',
            field=models.CharField(default='sent', max_length=30),
        ),
    ]
