# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_auto_20170207_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='handler',
            field=models.CharField(default='Test_1', max_length=50),
        ),
    ]
